config/routes.rb
Rails.application.routes.draw do
  get 'comments/create'
  devise_for :users
  devise_for :admins,skip: :registrations
  devise_scope :admin do
    get 'admin', to: 'devise/sessions#new'
  end
  namespace :api do
  mount_devise_token_auth_for 'User', at: 'auth'
  resources :posts, only: [:create, :show, :index, :destroy, :update]
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  resources :posts
  resources :comments, only: [:create]
  root "posts#index"
  # Defines the root path route ("/")
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates :body, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :body, :title, presence: true
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
  include DeviseTokenAuth::Concerns::User
  has_many :posts
  has_many :comments, through: :posts


  def user_owns_post?(post_id)
   post = Post.where(id:post_id)[0]
   if post.nil?
    nil
   elsif self.id != post.user_id
    false
   else
    true
   end
  end
end

app/controllers/api/application_controller.rb
class Api::ApplicationController < ActionController::API
  include DeviseTokenAuth::Concerns::SetUserByToken
end

app/controllers/api/posts_controller.rb
class Api::PostsController < Api::ApplicationController
  before_action :authenticate_api_user!

  def index
    posts = Post.all
    render json: posts
  end

  def show
    post = Post.find(params[:id])
    render json: post
  end

  def create
    user = current_api_user
    post = user.posts.build(post_params)
    if post.save
      render json: post
    else
      render json: :unprocessable_entity, status: :unprocessable_entity
    end
  end

  def update
    user = current_api_user
    post_id = params[:id]
    if response = user.user_owns_post?(post_id)
      Post.update(post_id,post_params)
      render json: Post.find(post_id)
    else
      render json: 'You can edit only your own posts.', status: 401 if !response.nil?
      render json: 'Post does not exist.', status: 404 if response.nil?
    end
  end

  def destroy
    user = current_api_user
    post_id = params[:id]
    if response = user.user_owns_post?(post_id)
      Post.destroy(post_id)
      render json: 'Post successfully deleted'
    else
      render json: 'You can delete only your own posts.', status: 401 if !response.nil?
      render json: 'Post does not exist.', status: 404 if response.nil?
    end
  end
  private

  def post_params
    params.require(:post).permit(:title,:body)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 protect_from_forgery with: :exception, if: :verify_from_api

 def verify_from_api
  params[:controller].split('/')[0] != 'devise_token_auth'
 end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  def create
    comment = Comment.new(comment_params)
    if comment.save
      redirect_to posts_path
    else
      redirect_to posts_path, status: :unprocessable_entity
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :user_id,:post_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit,:destroy,:update]
  def index
    @current_user = current_user
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    post = current_user.posts.build(post_params)
    if post.save
      redirect_to posts_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    post = Post.find(params[:id])
   if post.update(post_params)
     redirect_to posts_path
   else
    render :edit, status: :unprocessable_entity
   end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to posts_path
  end

  def post_params
    params.require(:post).permit(:title,:body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav>
      <%if user_signed_in? || admin_signed_in?%>
        <%if user_signed_in?%>
          <%= button_to 'Sign out', destroy_user_session_path, method: :delete%>
        <%else%>
        <%= button_to 'Sign out', destroy_admin_session_path, method: :delete %>
        <%end%>
        <%else%>
        <%= button_to 'Sign in', new_user_session_path, method: :get%>
        <%= button_to 'Sign up', new_user_registration_path, method: :get%>
      <%end%>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<%= form_with model: @post, method: :patch do |f| %>
  <%= f.label :title, 'Title' %>
  <%= f.text_field :title %>
  <%= f.label :body, 'Description' %>
  <%= f.text_field :body %>
  <%= hidden_field_tag :id, params[:id] %>
  <%= f.submit %>
<%end%>

app/views/posts/index.html.erb
<nav>
  <%= button_to 'Create post', new_post_path, method: :get%>
</nav>

<% @posts.each do |post|%>
  <div class="post">
    <%if admin_signed_in? || user_signed_in?%>
  <% if admin_signed_in? ||@current_user.id == post.user_id%>
  <%= button_to 'Edit post', edit_post_path(post), method: :get %>
  <%= button_to 'Delete post', post_path(post), method: :delete%>
    <%end%>
   <%end%>
 
    <%= "Title: #{post.title}" %>
    <%= "Description #{post.body}"%>
      <div class="comments-section">
          <% if post.comments.any?%>
              <div class="comments">
                <ul></ul>
                <%post.comments.each do |comment|%>
                  <li><%= comment.body%></li>
                <%end%>
                <ul></ul>
              </div>
          <%end%>
        <%= form_with model: Comment.new , method: :post do |f|%>
            <%= f.text_field :body %>

            <%= f.hidden_field :post_id, value:post.id%>
            <% if user_signed_in?%>
            <%= f.hidden_field :user_id, value:@current_user.id %>
            <%end%>
            <%= f.submit 'Send comment' %>
        <%end%>
      </div>
  </div>
<%end%>

app/views/posts/new.html.erb
<%= form_with model: @post, method: :post do |f|%>
  <%= f.label :title, 'Title' %>
  <%= f.text_field :title %>
  <%= f.label :body, 'Description' %>
  <%= f.text_field :body %>
  <%= f.submit %>
<%end%>